### ISSUE TITLE
No model folder found in models/OmniGen/

### ISSUE THREAD

**Issue by postmrtm** [AIFSH/OmniGen-ComfyUI#26]
I've manually downloaded all the required files per the link provided to huggingspace and no matter where i place them (used multiple instructions from here and other articles) i get a "No model folder found in models/OmniGen/"
I've put the files in my generic Models folder which is loaded as part of the folder yaml for comfyui - doesnt work.
I've put the files in my comfyui/models folder - doesnt work.
I've named the folder these names - OmniGen, OmniGen-v1 - doesnt work.
I've placed the omnigen folder under - LLM models and then LLM under comfyui/models - doesnt work.
Using the example T2I workflow provided in the node.

What am I missing or doing wrong? :(
Thank you for your time and hard work.

**Comment by PrometheusDante** [comment]
ComfyUI\ComfyUI\models\OmniGen\OmniGen-v1
![screenshot](https://github.com/user-attachments/assets/7e9b6071-8fbf-444f-8f75-e09889f2aec4)

**Comment by postmrtm** [comment]
@PrometheusDante Thank you!
